# Generated by Django 2.2.2 on 2021-01-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='脚本项目标题')),
                ('path', models.CharField(max_length=32, unique=True, verbose_name='脚本项目路径')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '脚本分类',
                'verbose_name_plural': '脚本分类',
                'db_table': 'task_platform_script_project',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作用户')),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('task_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='执行类型')),
                ('task_host', models.CharField(blank=True, max_length=1020, null=True, verbose_name='目标主机/组')),
                ('task_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='任务名称')),
                ('task_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务ID')),
                ('crontab_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='定时任务ID')),
                ('task_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务状态')),
                ('script_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='执行脚本')),
                ('script_cmd', models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行命令')),
                ('task_code', models.IntegerField(blank=True, null=True, verbose_name='脚本返回状态码')),
                ('task_result', models.TextField(blank=True, null=True, verbose_name='返回结果')),
                ('run_time', models.IntegerField(blank=True, null=True, verbose_name='脚本运行时长(s)')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
                'db_table': 'task_platform_history',
            },
        ),
        migrations.CreateModel(
            name='TaskScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='任务名称')),
                ('file_name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='脚本名称')),
                ('exec_unm', models.IntegerField(default=0, verbose_name='执行次数')),
                ('src_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='上传用户')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_platform.ScriptProject', verbose_name='所属脚本项目')),
            ],
            options={
                'verbose_name': '脚本任务',
                'verbose_name_plural': '脚本任务',
                'db_table': 'task_platform_task_script',
            },
        ),
    ]
