# Generated by Django 2.2.2 on 2021-01-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskScript',
            new_name='ScriptFile',
        ),
        migrations.AlterModelTable(
            name='scriptfile',
            table='task_platform_script_file',
        ),
    ]
