# Generated by Django 2.2.2 on 2021-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0002_auto_20210115_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(blank=True, choices=[(0, 'script'), (1, 'playbook')], null=True, verbose_name='脚本类型script/playbook')),
                ('src_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作用户')),
                ('source_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='原任务名')),
                ('source_project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='原项目名')),
                ('source_project_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='原项目Path')),
                ('source_file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='原脚本/包名')),
                ('path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='回收站中的路径')),
            ],
            options={
                'verbose_name': '任务回收站',
                'verbose_name_plural': '任务回收站',
                'db_table': 'task_platform_bin',
            },
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='run_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ansible'), (1, 'ssh')], null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_type',
            field=models.IntegerField(blank=True, choices=[(0, '脚本任务'), (1, '剧本任务'), (2, '定时任务')], null=True, verbose_name='执行的任务类型'),
        ),
    ]
