# Generated by Django 2.2.2 on 2021-01-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0003_auto_20210115_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目标题')),
                ('path', models.CharField(max_length=32, verbose_name='项目路径')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Ansible项目',
                'verbose_name_plural': 'Ansible项目',
                'db_table': 'task_platform_absible_project',
            },
        ),
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作业名称')),
                ('exec_unm', models.IntegerField(default=0, verbose_name='执行次数')),
                ('src_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作用户')),
                ('file_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='playbook剧本')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_platform.AnsibleProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'palybook',
                'verbose_name_plural': 'palybook',
                'db_table': 'task_platform_absible_playbook',
            },
        ),
        migrations.CreateModel(
            name='AnsibleParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='变量组名')),
                ('param', models.CharField(blank=True, max_length=120, null=True, verbose_name='配置参数')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_platform.AnsiblePlaybook', verbose_name='所属作业')),
            ],
            options={
                'verbose_name': 'a任务参数',
                'verbose_name_plural': 'a任务参数',
                'db_table': 'task_platform_absible_parameter',
            },
        ),
    ]
