# Generated by Django 2.2.2 on 2021-01-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0004_ansibleparameter_ansibleplaybook_ansibleproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleparameter',
            name='src_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='操作用户'),
        ),
    ]
