# Generated by Django 2.2.2 on 2021-01-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0005_ansibleparameter_src_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleparameter',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_platform.AnsiblePlaybook', verbose_name='所属作业'),
        ),
    ]
