# Generated by Django 2.2.2 on 2021-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0006_auto_20210115_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleproject',
            name='src_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上传用户'),
        ),
        migrations.AddField(
            model_name='scriptproject',
            name='src_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上传用户'),
        ),
    ]
