# Generated by Django 2.2.2 on 2021-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0008_auto_20210119_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcrontab',
            name='task_status',
            field=models.BooleanField(default=True),
        ),
    ]
