# Generated by Django 2.2.2 on 2021-01-24 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0009_taskcrontab_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansibleparameter',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='ansibleplaybook',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='ansibleproject',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='scriptfile',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='scriptproject',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='ansibleparameter',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='ansibleplaybook',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='ansibleproject',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='scriptfile',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='scriptproject',
            name='latest_date',
        ),
        migrations.AddField(
            model_name='ansibleparameter',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='ansibleparameter',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='ansibleproject',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='ansibleproject',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='scriptfile',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='scriptfile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='scriptproject',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='scriptproject',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='taskcrontab',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcrontab',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='taskcrontab',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='taskrecycle',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecycle',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='taskrecycle',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
    ]
