# Generated by Django 2.2.2 on 2021-01-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目标题')),
                ('path', models.CharField(max_length=32, verbose_name='项目路径')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
            ],
            options={
                'verbose_name': 'Ansible项目',
                'verbose_name_plural': 'Ansible项目',
                'db_table': 'task_absible_project',
            },
        ),
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='定时任务名称')),
                ('task_remarks', models.CharField(max_length=32, verbose_name='定时任务备注')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'task_crontab',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('src_ip', models.GenericIPAddressField(verbose_name='来源IP')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('task_status', models.CharField(max_length=128, verbose_name='任务状态')),
                ('script_file', models.CharField(max_length=128, verbose_name='执行脚本')),
                ('script_cmd', models.CharField(max_length=128, verbose_name='执行命令')),
                ('task_code', models.IntegerField(verbose_name='脚本返回状态')),
                ('task_result', models.TextField(verbose_name='返回结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
                'db_table': 'task_history',
            },
        ),
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='脚本项目标题')),
                ('path', models.CharField(max_length=32, unique=True, verbose_name='脚本项目路径')),
            ],
            options={
                'verbose_name': '脚本分类',
                'verbose_name_plural': '脚本分类',
                'db_table': 'task_project',
            },
        ),
        migrations.CreateModel(
            name='TaskScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('script_name', models.CharField(max_length=32, verbose_name='脚本名称')),
                ('exec_unm', models.IntegerField(default=0, verbose_name='执行次数')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskProject', verbose_name='所属脚本项目')),
            ],
            options={
                'verbose_name': '脚本任务',
                'verbose_name_plural': '脚本任务',
                'db_table': 'task_script',
            },
        ),
    ]
