# Generated by Django 2.2.2 on 2021-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210105_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscript',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='script_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='脚本名称'),
        ),
    ]
