# Generated by Django 2.2.2 on 2021-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskhistory_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_host',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='目标主机/组'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行类型'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='脚本返回状态码'),
        ),
    ]
