# Generated by Django 2.2.2 on 2021-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210106_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='run_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='脚本运行时长(s)'),
        ),
    ]
