# Generated by Django 2.2.2 on 2021-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210106_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='script_cmd',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行命令'),
        ),
    ]
