# Generated by Django 2.2.2 on 2021-01-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210106_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作业名称')),
                ('playbook', models.CharField(blank=True, max_length=120, null=True, verbose_name='playbook剧本')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.AnsibleProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'palybook',
                'verbose_name_plural': 'palybook',
                'db_table': 'task_absible_playbook',
            },
        ),
    ]
