# Generated by Django 2.2.2 on 2021-01-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_ansibleplaybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleExtravars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='变量组名')),
                ('vers', models.CharField(blank=True, max_length=120, null=True, verbose_name='配置参数')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.AnsiblePlaybook', verbose_name='所属作业')),
            ],
            options={
                'verbose_name': 'a任务参数',
                'verbose_name_plural': 'a任务参数',
                'db_table': 'task_absible_extravars',
            },
        ),
    ]
