# Generated by Django 2.2.2 on 2021-01-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_ansibleextravars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansibleextravars',
            old_name='job',
            new_name='playbook',
        ),
    ]
