# Generated by Django 2.2.2 on 2021-01-09 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20210109_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansibleplaybook',
            old_name='playbook',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='exec_unm',
            field=models.IntegerField(default=0, verbose_name='执行次数'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='latest_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
