# Generated by Django 2.2.2 on 2021-01-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20210109_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskscript',
            name='script_name',
        ),
    ]
