# Generated by Django 2.2.2 on 2021-01-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_taskscript_script_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskscript',
            old_name='script_name',
            new_name='file_name',
        ),
    ]
