# Generated by Django 2.2.2 on 2021-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20210109_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecycle',
            name='source_field',
        ),
        migrations.AddField(
            model_name='taskrecycle',
            name='source_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='原任务名'),
        ),
    ]
