# Generated by Django 2.2.2 on 2021-01-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20210109_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrecycle',
            options={'verbose_name': 'a任务参数', 'verbose_name_plural': 'a任务参数'},
        ),
        migrations.RenameField(
            model_name='taskrecycle',
            old_name='source_file',
            new_name='source_file_name',
        ),
        migrations.RenameField(
            model_name='taskrecycle',
            old_name='source_project',
            new_name='source_project_path',
        ),
        migrations.AlterModelTable(
            name='taskrecycle',
            table='task_recycle_bin',
        ),
    ]
