# Generated by Django 2.2.2 on 2021-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_auto_20210109_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrecycle',
            options={'verbose_name': '任务回收站', 'verbose_name_plural': '任务回收站'},
        ),
        migrations.AddField(
            model_name='taskrecycle',
            name='source_project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='原项目名'),
        ),
    ]
