# Generated by Django 2.2.2 on 2021-01-12 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20210109_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontabtask',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='crontabtask',
            name='task_remarks',
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='remarks',
            field=models.TextField(default='q', verbose_name='定时任务备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='run_type',
            field=models.CharField(default=1, max_length=128, verbose_name='执行方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='task_args',
            field=models.CharField(default='222', max_length=128, verbose_name='参数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='task_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='执行脚本'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='task_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='任务类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='tast_hosts',
            field=models.CharField(default=2, max_length=2048, verbose_name='目标主机'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crontabtask',
            name='task_id',
            field=models.CharField(max_length=128, verbose_name='定时任务任务ID'),
        ),
    ]
