# Generated by Django 2.2.2 on 2021-01-13 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20210112_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontabtask',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='crontabtask',
            old_name='task_type',
            new_name='task_lib',
        ),
        migrations.RemoveField(
            model_name='crontabtask',
            name='tast_hosts',
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='hosts_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='hosts文件'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='crontab_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='定时任务ID'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='任务ID'),
        ),
    ]
