# Generated by Django 2.2.2 on 2021-01-13 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20210113_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontabtask',
            name='task_hosts',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='主机列表'),
            preserve_default=False,
        ),
    ]
