# Generated by Django 2.2.2 on 2021-01-15 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_crontabtask_task_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecycle',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
