# Generated by Django 2.2.2 on 2021-01-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_taskrecycle_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibleextravars',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='ansibleplaybook',
            name='project',
        ),
        migrations.DeleteModel(
            name='CrontabTask',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
        migrations.DeleteModel(
            name='TaskRecycle',
        ),
        migrations.RemoveField(
            model_name='taskscript',
            name='project',
        ),
        migrations.DeleteModel(
            name='AnsibleExtravars',
        ),
        migrations.DeleteModel(
            name='AnsiblePlaybook',
        ),
        migrations.DeleteModel(
            name='AnsibleProject',
        ),
        migrations.DeleteModel(
            name='TaskProject',
        ),
        migrations.DeleteModel(
            name='TaskScript',
        ),
    ]
