# Generated by Django 2.2.2 on 2021-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='manage_ip',
        ),
        migrations.RemoveField(
            model_name='server',
            name='manage_ip',
        ),
    ]
