# Generated by Django 2.2.2 on 2021-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210102_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='ssh用户名')),
                ('password', models.CharField(max_length=32, verbose_name='ssh用户密码')),
                ('port', models.IntegerField(verbose_name='ssh端口')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='ssh',
            field=models.ManyToManyField(blank=True, to='cmdb.SshUser', verbose_name='绑定的ssh账户信息'),
        ),
    ]
