# Generated by Django 2.2.2 on 2021-01-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210102_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SshUser',
            new_name='SSH',
        ),
        migrations.AlterModelOptions(
            name='ssh',
            options={'verbose_name': '设备联系人表', 'verbose_name_plural': '设备联系人表'},
        ),
        migrations.AlterModelTable(
            name='ssh',
            table='cmdb_ssh',
        ),
    ]
