# Generated by Django 2.2.2 on 2021-01-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210102_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssh',
            options={'verbose_name': 'ssh表', 'verbose_name_plural': 'ssh表'},
        ),
    ]
