# Generated by Django 2.2.2 on 2021-01-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20210102_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ssh',
        ),
        migrations.AddField(
            model_name='asset',
            name='ssh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.SSH', verbose_name='绑定的ssh账户信息'),
        ),
    ]
