# Generated by Django 2.2.2 on 2021-01-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=32, verbose_name='登录用户')),
                ('src_ip', models.CharField(max_length=50, verbose_name='来源IP')),
                ('task_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='任务类型')),
                ('time_task_start', models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间')),
                ('time_task_finished', models.DateTimeField(auto_now_add=True, verbose_name='任务结束时间')),
                ('cmd_object', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作对象')),
                ('cmd', models.TextField(verbose_name='执行命令')),
                ('cmd_result', models.CharField(max_length=10, verbose_name='命令结果')),
                ('cmd_detail', models.TextField(blank=True, null=True, verbose_name='结果详情')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
                'db_table': 'absible_history',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目标题')),
                ('path', models.CharField(max_length=32, verbose_name='项目路径')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'absible_project',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作业名称')),
                ('playbook', models.CharField(blank=True, max_length=120, null=True, verbose_name='playbook剧本')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'absible_job',
            },
        ),
        migrations.CreateModel(
            name='Extravars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='变量组名')),
                ('vers', models.CharField(blank=True, max_length=120, null=True, verbose_name='配置参数')),
                ('online_status', models.BooleanField(default=True, verbose_name='激活状态')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible.Job', verbose_name='所属作业')),
            ],
            options={
                'verbose_name': '任务参数',
                'verbose_name_plural': '任务参数',
                'db_table': 'absible_extravars',
            },
        ),
    ]
